version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_customer_db
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mongodb:
    image: mongo:6.0
    container_name: banking-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  zipkin:
    image: openzipkin/zipkin
    container_name: banking-zipkin
    ports:
      - "9411:9411"

volumes:
  mysql_data:
  mongo_data:
